-- migrate:up
INSERT    INTO diagnoses (icd_code, name)
VALUES    ('A09.9', 'Viêm dạ dày ruột nhiễm trùng'),
          ('A16.9', 'Lao phổi không xác định'),
          ('A41.9', 'Nhiễm trùng huyết không xác định'),
          ('B15.9', 'Viêm gan A'),
          ('B20', 'HIV/AIDS'),
          ('B34.9', 'Nhiễm virus không xác định'),
          ('D50.9', 'Thiếu máu do thiếu sắt'),
          ('D57.9', 'Bệnh hồng cầu hình liềm'),
          ('D61.9', 'Suy tủy xương'),
          ('D64.9', 'Thiếu máu không rõ nguyên nhân'),
          ('D69.9', 'Rối loạn đông máu'),
          ('D84.9', 'Suy giảm miễn dịch'),
          ('E03.9', 'Suy giáp'),
          ('E04.9', 'Bướu giáp không độc'),
          ('E11.9', 'Đái tháo đường type 2'),
          ('E78.5', 'Rối loạn lipid máu'),
          ('E88.9', 'Rối loạn chuyển hóa khác'),
          ('G20', 'Bệnh Parkinson'),
          ('G25.9', 'Rối loạn vận động'),
          ('G35', 'Đa xơ cứng'),
          ('G40.9', 'Động kinh không xác định'),
          ('G43.9', 'Đau nửa đầu (Migraine)'),
          ('I10', 'Tăng huyết áp nguyên phát'),
          ('I25.1', 'Bệnh mạch vành xơ vữa'),
          ('I48', 'Rung nhĩ'),
          ('I50.9', 'Suy tim không rõ nguyên nhân'),
          ('I73.9', 'Bệnh mạch máu ngoại biên'),
          ('J15.9', 'Viêm phổi do vi khuẩn'),
          ('J18.9', 'Viêm phổi không xác định'),
          ('J20.9', 'Viêm phế quản cấp'),
          ('J44.9', 'COPD (Bệnh phổi tắc nghẽn mạn tính)'),
          ('J45.9', 'Hen phế quản không dị ứng'),
          ('K21.9', 'Trào ngược dạ dày-thực quản (GERD)'),
          ('K29.7', 'Viêm dạ dày mạn'),
          ('K57.3', 'Viêm túi thừa đại tràng'),
          ('K58.9', 'Hội chứng ruột kích thích (IBS)'),
          ('K76.0', 'Gan nhiễm mỡ không do rượu'),
          ('L40.9', 'Vẩy nến'),
          ('M06.9', 'Viêm khớp dạng thấp'),
          ('M15.9', 'Thoái hóa đa khớp'),
          ('M17.9', 'Thoái hóa khớp gối'),
          ('M32.9', 'Lupus ban đỏ hệ thống'),
          ('M47.9', 'Thoái hóa cột sống'),
          ('M54.5', 'Đau thắt lưng'),
          ('M79.7', 'Đau cơ xơ hóa (Fibromyalgia)'),
          ('N18.9', 'Bệnh thận mạn'),
          ('N20.9', 'Sỏi thận'),
          ('N39.0', 'Nhiễm trùng tiểu'),
          ('N40', 'Phì đại tuyến tiền liệt'),
          ('T78.4', 'Dị ứng không xác định');

INSERT    INTO medications (name, generic_name, med_type, strength, route_of_administration, manufacturer)
VALUES   
          -- 1-10: Thuốc giảm đau/hạ sốt
          ('Panadol', 'Paracetamol', 'viên nén', '500mg', 'uống', 'GSK'),
          ('Efferalgan', 'Paracetamol', 'viên sủi', '500mg', 'uống', 'Sanofi'),
          ('Hapacol', 'Paracetamol', 'viên nén', '650mg', 'uống', 'DHG Pharma'),
          ('Ibuprofen', 'Ibuprofen', 'viên nang', '400mg', 'uống', 'Stada'),
          ('Alaxan', 'Ibuprofen + Paracetamol', 'viên nén', '400mg/325mg', 'uống', 'United Pharma'),
          ('Tylenol', 'Paracetamol', 'siro', '160mg/5ml', 'uống', 'Johnson & Johnson'),
          ('Doliprane', 'Paracetamol', 'viên đặt', '300mg', 'đặt hậu môn', 'Sanofi'),
          ('Arcoxia', 'Etoricoxib', 'viên nén', '90mg', 'uống', 'MSD'),
          ('Celebrex', 'Celecoxib', 'viên nang', '200mg', 'uống', 'Pfizer'),
          ('Voltaren', 'Diclofenac', 'gel', '1%', 'bôi ngoài da', 'Novartis'),
          -- 11-20: Kháng sinh
          ('Augmentin', 'Amoxicillin + Clavulanate', 'viên nén', '875mg/125mg', 'uống', 'GSK'),
          ('Amoxicillin', 'Amoxicillin', 'viên nang', '500mg', 'uống', 'Stada'),
          ('Cephalexin', 'Cephalexin', 'viên nén', '500mg', 'uống', 'VN Pharma'),
          ('Azithromycin', 'Azithromycin', 'viên nén', '500mg', 'uống', 'Pfizer'),
          ('Ciprofloxacin', 'Ciprofloxacin', 'viên nén', '500mg', 'uống', 'Bayer'),
          ('Biseptol', 'Cotrimoxazole', 'viên nén', '480mg', 'uống', 'Sanofi'),
          ('Zinnat', 'Cefuroxime', 'viên nén', '500mg', 'uống', 'GSK'),
          ('Clavophar', 'Amoxicillin + Clavulanate', 'bột pha hỗn dịch', '600mg/5ml', 'uống', 'Pharimexco'),
          ('Ofloxacin', 'Ofloxacin', 'viên nén', '200mg', 'uống', 'Domesco'),
          ('Cefixime', 'Cefixime', 'viên nang', '400mg', 'uống', 'VN Pharma'),
          -- 21-30: Tiêu hóa
          ('Gastropulgite', 'Diosmectite', 'gói bột', '3g', 'uống', 'Sanofi'),
          ('Smecta', 'Diosmectite', 'gói bột', '3g', 'uống', 'Ipsen'),
          ('Omeprazole', 'Omeprazole', 'viên nang', '20mg', 'uống', 'AstraZeneca'),
          ('Lansoprazole', 'Lansoprazole', 'viên nén', '30mg', 'uống', 'Takeda'),
          ('Yumangel', 'Aluminium hydroxide', 'gel', '340mg/5ml', 'uống', 'Daewoong'),
          ('Motilium', 'Domperidone', 'viên nén', '10mg', 'uống', 'Janssen'),
          ('Primperan', 'Metoclopramide', 'viên nén', '10mg', 'uống', 'Sanofi'),
          ('Buscopan', 'Hyoscine N-butylbromide', 'viên nén', '10mg', 'uống', 'Sanofi'),
          ('Phosphalugel', 'Aluminium phosphate', 'gel', '20g', 'uống', 'Boehringer Ingelheim'),
          ('Debridat', 'Trimebutine', 'viên nén', '200mg', 'uống', 'Sanofi'),
          -- 31-40: Tim mạch
          ('Amlor', 'Amlodipine', 'viên nén', '5mg', 'uống', 'Pfizer'),
          ('Concor', 'Bisoprolol', 'viên nén', '5mg', 'uống', 'Merck'),
          ('Lasix', 'Furosemide', 'viên nén', '40mg', 'uống', 'Sanofi'),
          ('Plavix', 'Clopidogrel', 'viên nén', '75mg', 'uống', 'Sanofi'),
          ('Coversyl', 'Perindopril', 'viên nén', '5mg', 'uống', 'Servier'),
          ('Zestril', 'Lisinopril', 'viên nén', '10mg', 'uống', 'AstraZeneca'),
          ('Lipitor', 'Atorvastatin', 'viên nén', '20mg', 'uống', 'Pfizer'),
          ('Crestor', 'Rosuvastatin', 'viên nén', '10mg', 'uống', 'AstraZeneca'),
          ('Norvasc', 'Amlodipine', 'viên nén', '5mg', 'uống', 'Pfizer'),
          ('Cordarone', 'Amiodarone', 'viên nén', '200mg', 'uống', 'Sanofi'),
          -- 41-50: Thần kinh & Khác
          ('Stilux', 'Ginkgo biloba', 'viên nén', '40mg', 'uống', 'Pharbaco'),
          ('Tanganil', 'Acetylleucine', 'viên nén', '500mg', 'uống', 'Pierre Fabre'),
          ('Serc', 'Betahistine', 'viên nén', '16mg', 'uống', 'Abbott'),
          ('Neurobion', 'Vitamin B complex', 'viên nén', 'B1/B6/B12', 'uống', 'Merck'),
          ('Boganic', 'Tinh chất thảo dược', 'viên nang', '300mg', 'uống', 'Traphaco'),
          ('Glucosamine', 'Glucosamine sulfate', 'viên nén', '1500mg', 'uống', 'Dược Hậu Giang'),
          ('Prospan', 'Cao khô lá thường xuân', 'siro', '35mg/5ml', 'uống', 'Engelhard Arzneimittel'),
          ('Eugica', 'Eugica', 'viên ngậm', '2mg', 'ngậm', 'Dược phẩm OPC'),
          ('Otrivin', 'Xylometazoline', 'dung dịch nhỏ', '0.1%', 'nhỏ mũi', 'Novartis'),
          ('Sofmerol', 'Carboxymethyl cellulose', 'nước mắt nhân tạo', '0.5%', 'nhỏ mắt', 'Santen');

-- migrate:down
DELETE    FROM diagnoses;

DELETE    FROM medications;