basePath: /api/v1
definitions:
  models.AccountRecoverConfirmRequest:
    properties:
      citizen_id:
        type: string
      otp:
        type: string
    type: object
  models.AccountRecoverRequest:
    properties:
      citizen_id:
        type: string
      email:
        type: string
    type: object
  models.AccountRegisterRequest:
    properties:
      citizen_id:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      role:
        type: string
    type: object
  models.LoginRequest:
    properties:
      citizen_id:
        type: string
      password:
        type: string
    type: object
  models.LoginResponse:
    properties:
      token:
        type: string
    type: object
  models.PasswordResetRequest:
    properties:
      citizen_id:
        type: string
      new_password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for user authentication and registration
  title: Account API
  version: "1.0"
paths:
  /accounts/login:
    post:
      consumes:
      - application/json
      description: Return JWT token to auth user
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - accounts
  /accounts/recovery:
    post:
      consumes:
      - application/json
      description: Send recovery email to user
      parameters:
      - description: Recovery credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.AccountRecoverRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get important info to send recovery email
      tags:
      - accounts
  /accounts/recovery/confirm:
    post:
      consumes:
      - application/json
      description: Confirm recovery OTP
      parameters:
      - description: Recovery OTP
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.AccountRecoverConfirmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Confirm recovery OTP
      tags:
      - accounts
  /accounts/recovery/reset:
    put:
      consumes:
      - application/json
      description: Reset password after OTP verification
      parameters:
      - description: Password reset request
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.PasswordResetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Reset password
      tags:
      - accounts
  /accounts/register:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: User registration data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.AccountRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register new user
      tags:
      - accounts
swagger: "2.0"
